#!/bin/bash

#**********************************************************************
#                            XGrubPassword                            *
#---------------------------------------------------------------------*
# This program is free software; you can redistribute it and/or       *
# modify it under the terms of the GNU Lesser General Public License  *
# as published by the Free Software Foundation; either version 2      *
# of the License, or (at your option) any later version.              *
#                                                                     *
# This program is distributed in the hope that it will be useful,     *
# but WITHOUT ANY WARRANTY; without even the implied warranty of      *
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                *
#**********************************************************************

set -eu

# echo "DEBUG: xgrub-password-update called, $# args: $@"
# echo "DEBUG: xgrub-password-update called, $# args: $@" >> /tmp/xgrub-password-update.log

CONFFILE=/etc/xgrub-password/42_xgrub_password
OUTFILE=/etc/grub.d/42_xgrub_password
if [ -f "${CONFFILE}" ]; then

# 	echo "DEBUG: conf file ${CONFFILE}" >> /tmp/xgrub-password-update.log

	# set user/password
	cp "${CONFFILE}" "${OUTFILE}"
	chmod 0755 ${OUTFILE}

	# set 'unrestricted' to start os
	GRUB_FILE=/etc/grub.d/10_linux
	OLD_STR='CLASS="--class gnu-linux --class gnu --class os"'
	NEW_STR='CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
	sed 's/'"${OLD_STR}"'/'"${NEW_STR}"'/' -i "${GRUB_FILE}"
else
# 	echo "DEBUG: NO conf file ${CONFFILE}" >> /tmp/xgrub-password-update.log

	# remove user/password
	rm -f "${OUTFILE}"

	# remove 'unrestricted' to start os
	GRUB_FILE=/etc/grub.d/10_linux
	OLD_STR='CLASS="--class gnu-linux --class gnu --class os"'
	NEW_STR='CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
	sed 's/'"${NEW_STR}"'/'"${OLD_STR}"'/' -i "${GRUB_FILE}"
fi

# update grub
update-grub

sync
