#!/bin/bash

#**********************************************************************
#                            XGrubPassword                            *
#---------------------------------------------------------------------*
# This program is free software; you can redistribute it and/or       *
# modify it under the terms of the GNU Lesser General Public License  *
# as published by the Free Software Foundation; either version 2      *
# of the License, or (at your option) any later version.              *
#                                                                     *
# This program is distributed in the hope that it will be useful,     *
# but WITHOUT ANY WARRANTY; without even the implied warranty of      *
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                *
#**********************************************************************

set -eu

argc=$#
if [ ${argc} -lt 1 ] || [ ${argc} -gt 2 ]; then
	echo "Usage:"
	echo "	echo password|${0} <user name>"
	echo "	${0} <user name> <password>"
	exit 1
fi

function no_ctrlc {
	echo "CTRL-C"
	exit 1
}
function atexit {
	echo "Exit"
}
trap atexit EXIT
trap no_ctrlc SIGINT

GRUB_ADM=${1}
if [ "${GRUB_ADM}" == "" ]; then
	GRUB_ADM=xgrubadm
fi
# echo "GRUB_ADM=$GRUB_ADM"

if [ ${argc} -eq 2 ]; then
	GRUB_PWD=${2}
	# echo "GRUB_PWD1=${GRUB_PWD}"
else
	GRUB_PWD=$(cat -)
	# echo "GRUB_PWD2=${GRUB_PWD}"
fi

if [ "${GRUB_PWD}" == "" ]; then
	GRUB_PWD=GrubPassword
fi
# echo "GRUB_PWD=${GRUB_PWD}"

if [ ! -d /etc/xgrub-password/ ]; then
	mkdir -p /etc/xgrub-password/
fi
CONFFILE=/etc/xgrub-password/42_xgrub_password

mkpasswd=$(which grub-mkpasswd-pbkdf2 || true)
if [ "${mkpasswd}" == "" ]; then
	mkpasswd=/usr/bin/grub-mkpasswd-pbkdf2
fi
xgrub_pwd_upd=$(which xgrub-password-update || true)
if [ "${xgrub_pwd_upd}" == "" ]; then
	xgrub_pwd_upd=/usr/lib/xgrub-password/xgrub-password-update
fi

PWD=$(echo -e "${GRUB_PWD}\n${GRUB_PWD}" | ${mkpasswd} | awk '/grub.pbkdf/{print$NF}')

cat > ${CONFFILE} << EOF
#!/bin/sh
exec tail -n +3 \$0

# define superusers
set superusers="${GRUB_ADM}"
export superusers

# define users
password_pbkdf2 ${GRUB_ADM} ${PWD}
EOF
chmod 0755 ${CONFFILE}

${xgrub_pwd_upd}
