#!/bin/bash

#*******************************************************************************
#*                                XGrubPassword                                *
#*-----------------------------------------------------------------------------*
#*                                                                             *
#* Copyright (c) 2022 Ivan Danov                                               *
#*                                                                             *
#* MIT License                                                                 *
#*                                                                             *
#* Permission is hereby granted, free of charge, to any person obtaining a     *
#* copy of this software and associated documentation files (the "Software"),  *
#* to deal in the Software without restriction, including without limitation   *
#* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
#* and/or sell copies of the Software, and to permit persons to whom the       *
#* Software is furnished to do so, subject to the following conditions:        *
#*                                                                             *
#* The above copyright notice and this permission notice shall be included     *
#* in all copies or substantial portions of the Software.                      *
#*                                                                             *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS     *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
#* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
#* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
#* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
#* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
#* DEALINGS IN THE SOFTWARE.                                                   *
#*******************************************************************************

set -eu

echo "DEBUG: xgrub-password-update called, $# args: $*"
# echo "DEBUG: xgrub-password-update called, $# args: $*" >> /tmp/xgrub-password-update.log

CONFFILE=/etc/xgrub-password/42_xgrub_password
CONFFILE=inp_42_xgrub_password

GRUB_CFG_DIR=.
OUTFILE=42_xgrub_password

GRUB_FILE_10=${GRUB_CFG_DIR}/10_linux
OLD_STR_10='\--class gnu-linux --class gnu --class os'
NEW_STR_10='\--class gnu-linux --class gnu --unrestricted --class os'

GRUB_FILE_30=${GRUB_CFG_DIR}/30_os-prober
# shellcheck disable=SC2016
OLD_STR_30='\--class os \\$menuentry_id_option'
# shellcheck disable=SC2016
NEW_STR_30='\--class os --unrestricted \\$menuentry_id_option'

update_flag=0

# file old_str new_str
change_grub_conf_file()
{
	echo old "${1}": "$(grep -c "${2}" "${1}")"
	echo new "${1}": "$(grep -c "${3}" "${1}")"
	if [ "$(grep -c "${3}" "${1}")" -gt 0 ]; then
		sed 's/'"${3}"'/'"${2}"'/' -i "${1}"
		update_flag=1
		echo updated old "${1}": "$(grep -c "${2}" "${1}")"
		echo updated new "${1}": "$(grep -c "${3}" "${1}")"
	fi
}

if [ -f "${CONFFILE}" ]; then
	echo "DEBUG: conf file ${CONFFILE} found"

	# set user/password
	cp "${CONFFILE}" "${OUTFILE}"
	chmod 0755 "${OUTFILE}"

	# set 'unrestricted' to start os
	change_grub_conf_file "${GRUB_FILE_10}" "${OLD_STR_10}" "${NEW_STR_10}"

	# set 'unrestricted' to start other os-es
	change_grub_conf_file "${GRUB_FILE_30}" "${OLD_STR_30}" "${NEW_STR_30}"
else
	echo "DEBUG: conf file ${CONFFILE} not found"

	# remove user/password
	rm -f "${OUTFILE}"

	# remove 'unrestricted' to start os
	change_grub_conf_file "${GRUB_FILE_10}" "${NEW_STR_10}" "${OLD_STR_10}"

	# remove 'unrestricted' to start other os-es
	change_grub_conf_file "${GRUB_FILE_30}" "${NEW_STR_30}" "${OLD_STR_30}"
fi

if [ ${update_flag} -eq 1 ]; then
	# update grub
	echo update-grub
else
	echo "DEBUG: xgrub-password-update: update_flag=0" >> /tmp/xgrub-password-update.log
fi

sync
