#!/bin/bash

#*******************************************************************************
#*                                XGrubPassword                                *
#*-----------------------------------------------------------------------------*
#* based on https://github.com/covertsh/ubuntu-autoinstall-generator           *
#*                                                                             *
#* Copyright (c) 2022 Ivan Danov                                               *
#*                                                                             *
#* MIT License                                                                 *
#*                                                                             *
#* Permission is hereby granted, free of charge, to any person obtaining a     *
#* copy of this software and associated documentation files (the "Software"),  *
#* to deal in the Software without restriction, including without limitation   *
#* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
#* and/or sell copies of the Software, and to permit persons to whom the       *
#* Software is furnished to do so, subject to the following conditions:        *
#*                                                                             *
#* The above copyright notice and this permission notice shall be included     *
#* in all copies or substantial portions of the Software.                      *
#*                                                                             *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS     *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
#* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
#* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
#* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
#* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
#* DEALINGS IN THE SOFTWARE.                                                   *
#*******************************************************************************

set -eu

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root"
	exit 1
fi

argc=$#
if [ ${argc} -lt 1 ] || [ ${argc} -gt 2 ]; then
	echo "Usage:"
	echo "	echo password|${0} <user name>"
	echo "	${0} <user name> <password>"
	exit 1
fi

function no_ctrlc {
	echo "CTRL-C"
	exit 1
}
function atexit {
	echo "Exit"
}
trap atexit EXIT
trap no_ctrlc SIGINT

GRUB_ADM=${1}
if [ "${GRUB_ADM}" == "" ]; then
	GRUB_ADM=xgrubadm
fi
# echo "GRUB_ADM=$GRUB_ADM"

if [ ${argc} -eq 2 ]; then
	GRUB_PWD=${2}
	# echo "GRUB_PWD1=${GRUB_PWD}"
else
	GRUB_PWD=$(cat -)
	# echo "GRUB_PWD2=${GRUB_PWD}"
fi

if [ "${GRUB_PWD}" == "" ]; then
	GRUB_PWD=GrubPassword
fi
# echo "GRUB_PWD=${GRUB_PWD}"

if [ ! -d /etc/xgrub-password/ ]; then
	mkdir -p /etc/xgrub-password/
fi
CONFFILE=/etc/xgrub-password/42_xgrub_password

mkpasswd=$(which grub-mkpasswd-pbkdf2 || true)
if [ "${mkpasswd}" == "" ]; then
	mkpasswd=/usr/bin/grub-mkpasswd-pbkdf2
fi
xgrub_pwd_upd=$(which xgrub-password-update || true)
if [ "${xgrub_pwd_upd}" == "" ]; then
	xgrub_pwd_upd=/usr/lib/xgrub-password/xgrub-password-update
fi

PWD=$(echo -e "${GRUB_PWD}\n${GRUB_PWD}" | ${mkpasswd} | awk '/grub.pbkdf/{print$NF}')

cat > ${CONFFILE} << EOF
#!/bin/sh
exec tail -n +3 \$0

# define superusers
set superusers="${GRUB_ADM}"
export superusers

# define users
password_pbkdf2 ${GRUB_ADM} ${PWD}
EOF
chmod 0755 ${CONFFILE}

${xgrub_pwd_upd}
