#!/bin/bash -e

# shellcheck source=/dev/null
. /usr/share/debconf/confmodule

echo "DEBUG: xgrub-password-test prerm called, $# args: $@"
echo "DEBUG: xgrub-password-test prerm called, $# args: $@" >> /tmp/xgrub-password-update.log
case "$1" in
	remove)
		;;
	purge)
		;;
esac
