#!/bin/bash -e

# shellcheck source=/dev/null
. /usr/share/debconf/confmodule

echo "DEBUG: xgrub-password prerm called, $# args: $@"
echo "DEBUG: xgrub-password prerm called, $# args: $@" >> /tmp/xgrub-password-update.log
case "$1" in
	remove)
		rm -rf /etc/xgrub-password
		if [ -x /usr/lib/xgrub-password/xgrub-password-update ]; then
			# /usr/lib/xgrub-password/xgrub-password-update
		fi
		;;
	purge)
		;;
esac
