#!/bin/bash -e

# shellcheck source=/dev/null
. /usr/share/debconf/confmodule

# echo "DEBUG: xgrub-password prerm called, $# args: $@"
case "$1" in
	purge|remove)
		rm -rf /etc/xgrub-password
		/usr/lib/xgrub-password/xgrub-password-update
		;;
esac
